apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  namespace: cinemaabyss
  labels:
    app: events-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
        - name: events-service
          image: ghcr.io/alents/architecture-pro-cinemaabyss/events-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: kafka:9092
            - name: PORT
              value: "8080"
          resources:
            limits:
              cpu: "1000m"
              memory: "1000Mi"
            requests:
              cpu: "500m"
              memory: "528Mi"
          readinessProbe:
            httpGet:
              path: /api/events/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /api/events/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: cinemaabyss
spec:
  selector:
    app: events-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP